//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrinPlusPlus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrinPlusPlus.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align the QR within the frame.
        /// </summary>
        internal static string AlignQRCode {
            get {
                return ResourceManager.GetString("AlignQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        internal static string Blocks {
            get {
                return ResourceManager.GetString("Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Transaction.
        /// </summary>
        internal static string CancelTransaction {
            get {
                return ResourceManager.GetString("CancelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this Transaction?.
        /// </summary>
        internal static string CancelTransactionQuestion {
            get {
                return ResourceManager.GetString("CancelTransactionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coinbase.
        /// </summary>
        internal static string Coinbase {
            get {
                return ResourceManager.GetString("Coinbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment.
        /// </summary>
        internal static string Commitment {
            get {
                return ResourceManager.GetString("Commitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Peers.
        /// </summary>
        internal static string ConnectedPeers {
            get {
                return ResourceManager.GetString("ConnectedPeers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Slatepack Message.
        /// </summary>
        internal static string CopySlatepackMessage {
            get {
                return ResourceManager.GetString("CopySlatepackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account or use your wallet seed to restore a previous one.
        /// </summary>
        internal static string CreateOneOrRestoreIt {
            get {
                return ResourceManager.GetString("CreateOneOrRestoreIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Wallet.
        /// </summary>
        internal static string CreateWallet {
            get {
                return ResourceManager.GetString("CreateWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Wallet.
        /// </summary>
        internal static string DeleteWallet {
            get {
                return ResourceManager.GetString("DeleteWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive using Proximity.
        /// </summary>
        internal static string EnableProximity {
            get {
                return ResourceManager.GetString("EnableProximity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast. Private. Secure..
        /// </summary>
        internal static string FastPrivateSecure {
            get {
                return ResourceManager.GetString("FastPrivateSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize.
        /// </summary>
        internal static string Finalize {
            get {
                return ResourceManager.GetString("Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize Transaction.
        /// </summary>
        internal static string FinalizeTransaction {
            get {
                return ResourceManager.GetString("FinalizeTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        internal static string Headers {
            get {
                return ResourceManager.GetString("Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immature.
        /// </summary>
        internal static string Immature {
            get {
                return ResourceManager.GetString("Immature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernerls.
        /// </summary>
        internal static string Kernels {
            get {
                return ResourceManager.GetString("Kernels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from File.
        /// </summary>
        internal static string LoadFromFile {
            get {
                return ResourceManager.GetString("LoadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC.
        /// </summary>
        internal static string NFC {
            get {
                return ResourceManager.GetString("NFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        internal static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Interactivity.
        /// </summary>
        internal static string NonInteractive {
            get {
                return ResourceManager.GetString("NonInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Reachable.
        /// </summary>
        internal static string NotReachable {
            get {
                return ResourceManager.GetString("NotReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accounts were found.
        /// </summary>
        internal static string NoWalletFound {
            get {
                return ResourceManager.GetString("NoWalletFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text - QR Code - File .
        /// </summary>
        internal static string OfflineTransaction {
            get {
                return ResourceManager.GetString("OfflineTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openning Wallet, please wait....
        /// </summary>
        internal static string OpeningPleaseWait {
            get {
                return ResourceManager.GetString("OpeningPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Wallet.
        /// </summary>
        internal static string OpenWallet {
            get {
                return ResourceManager.GetString("OpenWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        internal static string Outputs {
            get {
                return ResourceManager.GetString("Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from Clipboard.
        /// </summary>
        internal static string PasteFromClipboard {
            get {
                return ResourceManager.GetString("PasteFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sending Method.
        /// </summary>
        internal static string PickSendingMethod {
            get {
                return ResourceManager.GetString("PickSendingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm.
        /// </summary>
        internal static string PleaseConfirm {
            get {
                return ResourceManager.GetString("PleaseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the POWER SAVER is DISABLED for this Application.
        /// </summary>
        internal static string PowerSaverMessage {
            get {
                return ResourceManager.GetString("PowerSaverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        internal static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reachable.
        /// </summary>
        internal static string Reachable {
            get {
                return ResourceManager.GetString("Reachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Transaction.
        /// </summary>
        internal static string ReceiveTransaction {
            get {
                return ResourceManager.GetString("ReceiveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repost.
        /// </summary>
        internal static string Repost {
            get {
                return ResourceManager.GetString("Repost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Existing Wallet.
        /// </summary>
        internal static string RestoreExistingWallet {
            get {
                return ResourceManager.GetString("RestoreExistingWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Wallet.
        /// </summary>
        internal static string RestoreWallet {
            get {
                return ResourceManager.GetString("RestoreWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning a QR Code.
        /// </summary>
        internal static string ScanningQRCode {
            get {
                return ResourceManager.GetString("ScanningQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScanQRCode.
        /// </summary>
        internal static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed Length.
        /// </summary>
        internal static string SeedLength {
            get {
                return ResourceManager.GetString("SeedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        internal static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Grins, please wait....
        /// </summary>
        internal static string SendingPleaseWait {
            get {
                return ResourceManager.GetString("SendingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Amount.
        /// </summary>
        internal static string SetAmount {
            get {
                return ResourceManager.GetString("SetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Address.
        /// </summary>
        internal static string ShareAddress {
            get {
                return ResourceManager.GetString("ShareAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Slatepack Message.
        /// </summary>
        internal static string ShareSlatepackMessage {
            get {
                return ResourceManager.GetString("ShareSlatepackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share as File.
        /// </summary>
        internal static string ShareSlatepackMessageAsFile {
            get {
                return ResourceManager.GetString("ShareSlatepackMessageAsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slate.
        /// </summary>
        internal static string Slate {
            get {
                return ResourceManager.GetString("Slate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slatepack.
        /// </summary>
        internal static string Slatepack {
            get {
                return ResourceManager.GetString("Slatepack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slatepack Address.
        /// </summary>
        internal static string SlatepackAddress {
            get {
                return ResourceManager.GetString("SlatepackAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slatepack Message.
        /// </summary>
        internal static string SlatepackMessage {
            get {
                return ResourceManager.GetString("SlatepackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slatepack Message File.
        /// </summary>
        internal static string SlatepackMessageFile {
            get {
                return ResourceManager.GetString("SlatepackMessageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slatepack Message Text.
        /// </summary>
        internal static string SlatepackMessageText {
            get {
                return ResourceManager.GetString("SlatepackMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPENDABLE.
        /// </summary>
        internal static string Spendable {
            get {
                return ResourceManager.GetString("Spendable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe Up to Send Grins 😬.
        /// </summary>
        internal static string SwipeUp2Send {
            get {
                return ResourceManager.GetString("SwipeUp2Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the Address to copy.
        /// </summary>
        internal static string TabToCopy {
            get {
                return ResourceManager.GetString("TabToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor Address.
        /// </summary>
        internal static string TorAddress {
            get {
                return ResourceManager.GetString("TorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Sent  〜(ᵐ‿ʷ)〜.
        /// </summary>
        internal static string TransactionSent {
            get {
                return ResourceManager.GetString("TransactionSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed.
        /// </summary>
        internal static string Unconfirmed {
            get {
                return ResourceManager.GetString("Unconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Messages.
        /// </summary>
        internal static string UsingInteractivity {
            get {
                return ResourceManager.GetString("UsingInteractivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using NFC.
        /// </summary>
        internal static string UsingNFC {
            get {
                return ResourceManager.GetString("UsingNFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the Node to be synced.
        /// </summary>
        internal static string WaitingSync {
            get {
                return ResourceManager.GetString("WaitingSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Seed.
        /// </summary>
        internal static string WalletSeed {
            get {
                return ResourceManager.GetString("WalletSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
